# Generated by Django 6.0.1 on 2026-01-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время первой отправки")),
                ("end_time", models.DateTimeField(auto_now=True, verbose_name="Дата и время окончания отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Создана", "Создана"),
                            ("Запущена", "Запущена"),
                            ("Завершена", "Завершена"),
                            ("Блокирована", "Блокирована"),
                        ],
                        default="Создана",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("is_block", models.BooleanField(default=False, verbose_name="Блокировка")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["start_time", "status"],
                "permissions": [
                    ("can_view_mailings_of_all_recipients", "can view mailings of all recipients"),
                    ("can_block_mailings", "can block mailings"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_time_of_attempt", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")),
                (
                    "status",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                        default="Не успешно",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("mail_server_response", models.TextField(verbose_name="Ответ почтового сервера")),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
                "ordering": ["date_time_of_attempt"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=150, verbose_name="Тема письма")),
                ("body_of_the_letter", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["subject"],
                "permissions": [("can_view_all_message", "can view all message")],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("full_name", models.CharField(max_length=100, verbose_name="Ф.И.О")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["full_name"],
                "permissions": [("can_view_mailings_of_all_recipients", "can view mailings of all recipients")],
            },
        ),
    ]
